#!/bin/bash

if [ ! -d "../out" ]; then
	mkdir "../out"
fi

javac -d ../out -cp ../src ../src/AI.java
cd ../out
jar cfe BeanMaster.jar AI *.class

cd ../scripts

if [[ "$OSTYPE" == "linux-gnu" ]]; then
	nodejs ./play.js
else
	node ./play.js
fi

